set(_CATKIN_CURRENT_PACKAGE "ni_slam")
set(ni_slam_VERSION "0.0.0")
set(ni_slam_MAINTAINER "jeffsan <wang.chen@zoho.com>")
set(ni_slam_PACKAGE_FORMAT "1")
set(ni_slam_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "nav_msgs")
set(ni_slam_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "nav_msgs")
set(ni_slam_BUILDTOOL_DEPENDS "catkin")
set(ni_slam_BUILDTOOL_EXPORT_DEPENDS )
set(ni_slam_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "nav_msgs")
set(ni_slam_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "nav_msgs")
set(ni_slam_TEST_DEPENDS )
set(ni_slam_DOC_DEPENDS )
set(ni_slam_URL_WEBSITE "")
set(ni_slam_URL_BUGTRACKER "")
set(ni_slam_URL_REPOSITORY "")
set(ni_slam_DEPRECATED "")