// Generated by gencpp from file ni_slam/MapInfo.msg
// DO NOT EDIT!


#ifndef NI_SLAM_MESSAGE_MAPINFO_H
#define NI_SLAM_MESSAGE_MAPINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace ni_slam
{
template <class ContainerAllocator>
struct MapInfo_
{
  typedef MapInfo_<ContainerAllocator> Type;

  MapInfo_()
    : header()
    , resolution(0.0)
    , width(0)
    , height(0)
    , origin()  {
    }
  MapInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , resolution(0.0)
    , width(0)
    , height(0)
    , origin(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _resolution_type;
  _resolution_type resolution;

   typedef uint32_t _width_type;
  _width_type width;

   typedef uint32_t _height_type;
  _height_type height;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _origin_type;
  _origin_type origin;





  typedef boost::shared_ptr< ::ni_slam::MapInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ni_slam::MapInfo_<ContainerAllocator> const> ConstPtr;

}; // struct MapInfo_

typedef ::ni_slam::MapInfo_<std::allocator<void> > MapInfo;

typedef boost::shared_ptr< ::ni_slam::MapInfo > MapInfoPtr;
typedef boost::shared_ptr< ::ni_slam::MapInfo const> MapInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ni_slam::MapInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ni_slam::MapInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ni_slam::MapInfo_<ContainerAllocator1> & lhs, const ::ni_slam::MapInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.resolution == rhs.resolution &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.origin == rhs.origin;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ni_slam::MapInfo_<ContainerAllocator1> & lhs, const ::ni_slam::MapInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ni_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ni_slam::MapInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ni_slam::MapInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ni_slam::MapInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ni_slam::MapInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ni_slam::MapInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ni_slam::MapInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ni_slam::MapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21930ed739995b1ba31aa9c9a8e1cc31";
  }

  static const char* value(const ::ni_slam::MapInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21930ed739995b1bULL;
  static const uint64_t static_value2 = 0xa31aa9c9a8e1cc31ULL;
};

template<class ContainerAllocator>
struct DataType< ::ni_slam::MapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ni_slam/MapInfo";
  }

  static const char* value(const ::ni_slam::MapInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ni_slam::MapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This hold basic information about the characterists of each sub-map the ni-slam\n"
"Header header \n"
"float32 resolution             # The map resolution [m/cell]\n"
"uint32 width                   # Map width [cells]\n"
"uint32 height                  # Map height [cells]\n"
"geometry_msgs/Pose origin      # The origin of the map.\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::ni_slam::MapInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ni_slam::MapInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.resolution);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.origin);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ni_slam::MapInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ni_slam::MapInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "resolution: ";
    Printer<float>::stream(s, indent + "  ", v.resolution);
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
    s << indent << "origin: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.origin);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NI_SLAM_MESSAGE_MAPINFO_H
